create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  submitted_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null,
  phone text not null,
  student_class text not null,
  message text not null default '',
  remote_address text,
  email_sent boolean not null default false,
  email_error text
);

create index if not exists inquiries_submitted_at_idx
  on public.inquiries (submitted_at desc);

alter table public.inquiries enable row level security;

-- The backend server should use a backend-only Supabase key.
-- No public insert policy is created here on purpose.

